
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: "https://192.168.50.1:9443/mutate-v1-pod"
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNzakNDQVpvQ0NRQ2V5ZnNqSGpUTGd6QU5CZ2txaGtpRzl3MEJBUXNGQURBYk1Sa3dGd1lEVlFRRERCQnQKZVdOaExtUmxabUYxYkhRdWMzWmpNQjRYRFRJeU1EZ3dOekV4TURBMU5Wb1hEVFE1TVRJeU16RXhNREExTlZvdwpHekVaTUJjR0ExVUVBd3dRYlhsallTNWtaV1poZFd4MExuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBSjZrOElDWHJkWnhZaW5Gam9OMGplUk04UkhIVWhSOUNTeEJ6aWtLSnY5LzJrTU8KV3U3NEc5R1QzMWJWNVpVZnBQNGdCa1FOREc2dzJYZUtzTElVcFJWVGRycnZ3cHZYRythNW1QSlMzTWNWMWo0cQplVDZwM2FFbFpKTG9JYXc5S29rRHBRR25NYWRGVy93RGhpMzMzUkM2TTRjL3FvdHZOSVY0Z0dDVDdGVDUzanNoCkNPSkpueWJudnNVbzZpc29STUdWM3Z4Z1o2SU9LNUwyUTExKzUrdjBlbUloZ1E2dzdvMXlQS0owWVE5bnBOa3kKMEtvUmFoVUdZbnh0VzVLdk96NEl5QTFpc2V5NzFZVzNkanN2NUVvUEgzQ3dBTk0vQkpuOFluZEQzWS9WZzFYYwpidU5Vb1RQcUdRNUJKQ1ZpeFlDT2RiRW9tSTR2b1Vjb2J0T09INDBDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGCkFBT0NBUUVBRWNSSjJRVEhnTDY2aGdLZVE0Q0hLZVNSOEtQMUNuQllaY2hvOWJRcXNvYjkrN085ZEpSRWRKaHAKT2VraGpTb3M5clUzczEzUm9uU1RzWDNRbkRvMngwR1VkcW9GdnljN3pEMGxCT2pSdFNNQ09wQ2xDdFNHRzBrQgpubTM2aVYvdEJXUTdaT0kzc1dJVEx0UEZxUW5VU1Q1eGI1Y3ZDcUxYNHRYazgvMjl2aStpZmhVekJRNkFzclhuCjlTNmZWVjNkcjE0Y1duc3F0MDlpUTZDUjIyMUhDT3dmN3RkS09lMVBEc2dnSkRRZXA3eHJhTFZmTnZUUlNZd0MKdExiamVsQ3IzZzZ5Zmd3R2QxK0pGbUZCRFhsREQ1ZXduT296WHVjRXUzemVFZlp0QjUvSUJuZzVTa0J5SFZVeAo2L1hLeG0veWZPNzJVa2l2NmdKUGdBcXpIekZPcGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  failurePolicy: Fail
  name: mmemcached.kb.io
  rules:
  - apiGroups: ["*"]
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: "https://192.168.50.1:9443/validate-v1-pod"
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNzakNDQVpvQ0NRQ2V5ZnNqSGpUTGd6QU5CZ2txaGtpRzl3MEJBUXNGQURBYk1Sa3dGd1lEVlFRRERCQnQKZVdOaExtUmxabUYxYkhRdWMzWmpNQjRYRFRJeU1EZ3dOekV4TURBMU5Wb1hEVFE1TVRJeU16RXhNREExTlZvdwpHekVaTUJjR0ExVUVBd3dRYlhsallTNWtaV1poZFd4MExuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBSjZrOElDWHJkWnhZaW5Gam9OMGplUk04UkhIVWhSOUNTeEJ6aWtLSnY5LzJrTU8KV3U3NEc5R1QzMWJWNVpVZnBQNGdCa1FOREc2dzJYZUtzTElVcFJWVGRycnZ3cHZYRythNW1QSlMzTWNWMWo0cQplVDZwM2FFbFpKTG9JYXc5S29rRHBRR25NYWRGVy93RGhpMzMzUkM2TTRjL3FvdHZOSVY0Z0dDVDdGVDUzanNoCkNPSkpueWJudnNVbzZpc29STUdWM3Z4Z1o2SU9LNUwyUTExKzUrdjBlbUloZ1E2dzdvMXlQS0owWVE5bnBOa3kKMEtvUmFoVUdZbnh0VzVLdk96NEl5QTFpc2V5NzFZVzNkanN2NUVvUEgzQ3dBTk0vQkpuOFluZEQzWS9WZzFYYwpidU5Vb1RQcUdRNUJKQ1ZpeFlDT2RiRW9tSTR2b1Vjb2J0T09INDBDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGCkFBT0NBUUVBRWNSSjJRVEhnTDY2aGdLZVE0Q0hLZVNSOEtQMUNuQllaY2hvOWJRcXNvYjkrN085ZEpSRWRKaHAKT2VraGpTb3M5clUzczEzUm9uU1RzWDNRbkRvMngwR1VkcW9GdnljN3pEMGxCT2pSdFNNQ09wQ2xDdFNHRzBrQgpubTM2aVYvdEJXUTdaT0kzc1dJVEx0UEZxUW5VU1Q1eGI1Y3ZDcUxYNHRYazgvMjl2aStpZmhVekJRNkFzclhuCjlTNmZWVjNkcjE0Y1duc3F0MDlpUTZDUjIyMUhDT3dmN3RkS09lMVBEc2dnSkRRZXA3eHJhTFZmTnZUUlNZd0MKdExiamVsQ3IzZzZ5Zmd3R2QxK0pGbUZCRFhsREQ1ZXduT296WHVjRXUzemVFZlp0QjUvSUJuZzVTa0J5SFZVeAo2L1hLeG0veWZPNzJVa2l2NmdKUGdBcXpIekZPcGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  failurePolicy: Fail
  name: vmemcached.kb.io
  rules:
    - apiGroups: ["*"]
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  sideEffects: None
