
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: "https://192.168.50.1:9443/mutate-v1-pod"
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0ekNDQWN1Z0F3SUJBZ0lKQU0yeTB0ZnFFUjJkTUEwR0NTcUdTSWIzRFFFQkJRVUFNQkF4RGpBTUJnTlYKQkFNTUJTNHVjM1pqTUI0WERUSXhNRFF4TWpBNU1EY3lPRm9YRFRJeE1EVXhNakE1TURjeU9Gb3dFREVPTUF3RwpBMVVFQXd3RkxpNXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRENtSTc2CkU5bDRPNWl0alFHbC9BWkp6UTY0Y3kwempCNC9YYndqcitieW1JMWRiQk1VSzkyaFVhbEpTS0tUR1BteXBOWFQKdy9CbVYwaWZzZ2xFQXZPbFZnY1o1WS96QVluWUh1SXJHS1d0dXp4bXVDY0k2SDBobTF5RTZ5VnhacVZCbkV2SQo0eTdQNjFXRU94aDZDZi8zUjBTK3pVNHpMSVlaWEdpQmV2YnNEeXA3VXY5a0VuNDFDM0sxRWJPY3I3a0ZyR0pSCks2NnlxNzFqUXR6UUM2bXBORm1TWUNjQmkwUm8zRnJ0V0daRUJrbEVVZWlINDJIQTd6QXJUNERGclRhS2tyL04KZHV1TENVUUFzelJOK1l1UXRrTlJYZURNT1lMTWw4TTdYclZ1bEtmLy9kZDhpQlR2Y1pWT2k4cWlHSHJVV0xJcwpJVEhYemlWYTFHcTlkaEVKQWdNQkFBR2pRREErTUFrR0ExVWRFd1FDTUFBd0N3WURWUjBQQkFRREFnWGdNQk1HCkExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1BOEdBMVVkRVFRSU1BYUhCTUNvTWdFd0RRWUpLb1pJaHZjTkFRRUYKQlFBRGdnRUJBR0Yzck1kajJSeVJTN1FnUDNmUGhtVUV5TWhIcEtxY2hIQ2lUTG5ZS1EzU09tQjRVTVFOck1NNApJelFyQ3QrUnFhODlCNnoxYWRCVGNSZFRtTU9lSC90ZThyVGhRZnY2YXhwQzY1MzcyRWdQR3Y4VUNLcC9mOWJICnFSdTZVd3pSN3RVeFVudnRtVVp2bWFaRHZWZEkyT3Q3bzdRdmpHWHV3Ti82bFlMQyswdzIvenBTWC90elBDZ0cKZTVrWW1RNzBsMGFxM3VnYVNaeFJicjZCOGZCcE1uRDBxNExzeXpWWWVjekZjcXhRQVkrd3UwVWJvK3ZRQ2ZhTQp0Z2xuWUdNTFhFWFY4dVdzWXpCaUswR2Zwcm5IblRPWW5TZzNoUjBtMXRSZUtnanR5cEk2TkY2Tk9UNXBLL2E0CjVyRnErZndUYWpnaXp2V2ZsNUttS1kwUlJ4YUZCTUU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  failurePolicy: Fail
  name: mmemcached.kb.io
  rules:
  - apiGroups: ["*"]
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: "https://192.168.50.1:9443/validate-v1-pod"
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0ekNDQWN1Z0F3SUJBZ0lKQU0yeTB0ZnFFUjJkTUEwR0NTcUdTSWIzRFFFQkJRVUFNQkF4RGpBTUJnTlYKQkFNTUJTNHVjM1pqTUI0WERUSXhNRFF4TWpBNU1EY3lPRm9YRFRJeE1EVXhNakE1TURjeU9Gb3dFREVPTUF3RwpBMVVFQXd3RkxpNXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRENtSTc2CkU5bDRPNWl0alFHbC9BWkp6UTY0Y3kwempCNC9YYndqcitieW1JMWRiQk1VSzkyaFVhbEpTS0tUR1BteXBOWFQKdy9CbVYwaWZzZ2xFQXZPbFZnY1o1WS96QVluWUh1SXJHS1d0dXp4bXVDY0k2SDBobTF5RTZ5VnhacVZCbkV2SQo0eTdQNjFXRU94aDZDZi8zUjBTK3pVNHpMSVlaWEdpQmV2YnNEeXA3VXY5a0VuNDFDM0sxRWJPY3I3a0ZyR0pSCks2NnlxNzFqUXR6UUM2bXBORm1TWUNjQmkwUm8zRnJ0V0daRUJrbEVVZWlINDJIQTd6QXJUNERGclRhS2tyL04KZHV1TENVUUFzelJOK1l1UXRrTlJYZURNT1lMTWw4TTdYclZ1bEtmLy9kZDhpQlR2Y1pWT2k4cWlHSHJVV0xJcwpJVEhYemlWYTFHcTlkaEVKQWdNQkFBR2pRREErTUFrR0ExVWRFd1FDTUFBd0N3WURWUjBQQkFRREFnWGdNQk1HCkExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1BOEdBMVVkRVFRSU1BYUhCTUNvTWdFd0RRWUpLb1pJaHZjTkFRRUYKQlFBRGdnRUJBR0Yzck1kajJSeVJTN1FnUDNmUGhtVUV5TWhIcEtxY2hIQ2lUTG5ZS1EzU09tQjRVTVFOck1NNApJelFyQ3QrUnFhODlCNnoxYWRCVGNSZFRtTU9lSC90ZThyVGhRZnY2YXhwQzY1MzcyRWdQR3Y4VUNLcC9mOWJICnFSdTZVd3pSN3RVeFVudnRtVVp2bWFaRHZWZEkyT3Q3bzdRdmpHWHV3Ti82bFlMQyswdzIvenBTWC90elBDZ0cKZTVrWW1RNzBsMGFxM3VnYVNaeFJicjZCOGZCcE1uRDBxNExzeXpWWWVjekZjcXhRQVkrd3UwVWJvK3ZRQ2ZhTQp0Z2xuWUdNTFhFWFY4dVdzWXpCaUswR2Zwcm5IblRPWW5TZzNoUjBtMXRSZUtnanR5cEk2TkY2Tk9UNXBLL2E0CjVyRnErZndUYWpnaXp2V2ZsNUttS1kwUlJ4YUZCTUU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  failurePolicy: Fail
  name: vmemcached.kb.io
  rules:
    - apiGroups: ["*"]
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  sideEffects: None
